name: Convert MLX to HTML and Sync

on:
  push:
    branches: [ main ]
    paths:
    - '**.mlx'

jobs:
  convert-and-sync:
    runs-on: self-hosted
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Get All Changed Files
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: Find changed mlx files
        id: getfile
        run: |
          files=$(echo "${{ steps.files.outputs.all }}" | grep -E '\.mlx$')
          echo "::set-output name=file::$files"

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Convert .mlx to .html
        run: matlab -batch "convertMlxToHtml('${{ steps.getfile.outputs.file }}')"

      - name: Give execute permission to the build script
        run: chmod +x build.sh

      - name: Run build.sh script
        run: ./build.sh '<username>/<gh-pages-repo>' ${{ secrets.PAT }} '${{ steps.getfile.outputs.file }}'
